// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfCPnlmzjehuvB0Rz5xqeRwJN67t8z1K8',
    appId: '1:868233758353:android:794e9c105e5507d96de130',
    messagingSenderId: '868233758353',
    projectId: 'shoe-ecommerce-1',
    storageBucket: 'shoe-ecommerce-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLEqSWqLlSJsO8oRSxTt_B4o8pUC1gj0',
    appId: '1:868233758353:ios:37b0a7d9d85e01d66de130',
    messagingSenderId: '868233758353',
    projectId: 'shoe-ecommerce-1',
    storageBucket: 'shoe-ecommerce-1.firebasestorage.app',
    iosClientId:
        '868233758353-l4i7l4aeu0pl4p63oa41cqui3a6bkal3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoeEcommerce',
  );
}
